// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5YmiHmJiy1nH1oSb4I-CvupDUCTjcc-0',
    appId: '1:700327700833:web:d0c56eb71533dde9a77d20',
    messagingSenderId: '700327700833',
    projectId: 'albion-online-tools-7f504',
    authDomain: 'albion-online-tools-7f504.firebaseapp.com',
    storageBucket: 'albion-online-tools-7f504.firebasestorage.app',
    measurementId: 'G-QYD2NJHCE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjoxN5nlAXpDe9OQxylD0DwAYQk1IZgA',
    appId: '1:700327700833:android:c8223717fa7f9432a77d20',
    messagingSenderId: '700327700833',
    projectId: 'albion-online-tools-7f504',
    storageBucket: 'albion-online-tools-7f504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhRAblsLXkL7aaIFeOVnzpaUmnWSBilA',
    appId: '1:700327700833:ios:777b210dacbbbb8da77d20',
    messagingSenderId: '700327700833',
    projectId: 'albion-online-tools-7f504',
    storageBucket: 'albion-online-tools-7f504.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAlbionTfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhRAblsLXkL7aaIFeOVnzpaUmnWSBilA',
    appId: '1:700327700833:ios:777b210dacbbbb8da77d20',
    messagingSenderId: '700327700833',
    projectId: 'albion-online-tools-7f504',
    storageBucket: 'albion-online-tools-7f504.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAlbionTfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5YmiHmJiy1nH1oSb4I-CvupDUCTjcc-0',
    appId: '1:700327700833:web:24a0b115410c2983a77d20',
    messagingSenderId: '700327700833',
    projectId: 'albion-online-tools-7f504',
    authDomain: 'albion-online-tools-7f504.firebaseapp.com',
    storageBucket: 'albion-online-tools-7f504.firebasestorage.app',
    measurementId: 'G-65Q380Y9T5',
  );
}
